// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Banner': typeof import("../components/Banner.vue")['default'],
    'BbsTabs': typeof import("../components/BbsTabs.vue")['default'],
    'BookList': typeof import("../components/BookList.vue")['default'],
    'Comment': typeof import("../components/Comment.vue")['default'],
    'CouponList': typeof import("../components/CouponList.vue")['default'],
    'CouponModal': typeof import("../components/CouponModal.vue")['default'],
    'CourseList': typeof import("../components/CourseList.vue")['default'],
    'Empty': typeof import("../components/Empty.vue")['default'],
    'FavaBtn': typeof import("../components/FavaBtn.vue")['default'],
    'GotoTop': typeof import("../components/GotoTop.vue")['default'],
    'HotCourseList': typeof import("../components/HotCourseList.vue")['default'],
    'ImageAd': typeof import("../components/ImageAd.vue")['default'],
    'ImageNav': typeof import("../components/ImageNav.vue")['default'],
    'ListCard': typeof import("../components/ListCard.vue")['default'],
    'LiveStatusBar': typeof import("../components/LiveStatusBar.vue")['default'],
    'NavBar': typeof import("../components/NavBar.vue")['default'],
    'PageFooter': typeof import("../components/PageFooter.vue")['default'],
    'PaperTestItems': typeof import("../components/PaperTestItems.vue")['default'],
    'PostList': typeof import("../components/PostList.vue")['default'],
    'Price': typeof import("../components/Price.vue")['default'],
    'QrCode': typeof import("../components/QrCode.vue")['default'],
    'SearchBar': typeof import("../components/SearchBar.vue")['default'],
    'Seckill': typeof import("../components/Seckill.vue")['default'],
    'SendCode': typeof import("../components/SendCode.vue")['default'],
    'TestPaperList': typeof import("../components/TestPaperList.vue")['default'],
    'TimeBox': typeof import("../components/TimeBox.vue")['default'],
    'Uploader': typeof import("../components/Uploader.vue")['default'],
    'DetailActiveBar': typeof import("../components/Detail/ActiveBar.vue")['default'],
    'DetailGroupWorks': typeof import("../components/Detail/GroupWorks.vue")['default'],
    'DetailMenu': typeof import("../components/Detail/Menu.vue")['default'],
    'DetailMenuItem': typeof import("../components/Detail/MenuItem.vue")['default'],
    'LoadingBookSkeletion': typeof import("../components/Loading/BookSkeletion.vue")['default'],
    'LoadingCourseSkeleton': typeof import("../components/Loading/CourseSkeleton.vue")['default'],
    'LoadingGroup': typeof import("../components/Loading/Group.vue")['default'],
    'LoadingSkeleton': typeof import("../components/Loading/Skeleton.vue")['default'],
    'PlayerAudio': typeof import("../components/Player/Audio.vue")['default'],
    'PlayerLive': typeof import("../components/Player/Live.vue")['default'],
    'PlayerVideo': typeof import("../components/Player/Video.vue")['default'],
    'UiImage': typeof import("../components/Ui/Image.vue")['default'],
    'UiMenu': typeof import("../components/Ui/Menu.vue")['default'],
    'UiMenuItem': typeof import("../components/Ui/MenuItem.vue")['default'],
    'UiTab': typeof import("../components/Ui/Tab.vue")['default'],
    'UiTabItem': typeof import("../components/Ui/TabItem.vue")['default'],
    'UserBuyList': typeof import("../components/User/BuyList.vue")['default'],
    'UserCouponList': typeof import("../components/User/CouponList.vue")['default'],
    'UserFavaList': typeof import("../components/User/FavaList.vue")['default'],
    'UserHistoryList': typeof import("../components/User/HistoryList.vue")['default'],
    'UserTestList': typeof import("../components/User/TestList.vue")['default'],
    'UiCardBody': typeof import("../components/Ui/Card/Body.vue")['default'],
    'UiCardFooter': typeof import("../components/Ui/Card/Footer.vue")['default'],
    'UiCardHeader': typeof import("../components/Ui/Card/Header.vue")['default'],
    'UiCard': typeof import("../components/Ui/Card/index.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyBanner': typeof import("../components/Banner.vue")['default'],
    'LazyBbsTabs': typeof import("../components/BbsTabs.vue")['default'],
    'LazyBookList': typeof import("../components/BookList.vue")['default'],
    'LazyComment': typeof import("../components/Comment.vue")['default'],
    'LazyCouponList': typeof import("../components/CouponList.vue")['default'],
    'LazyCouponModal': typeof import("../components/CouponModal.vue")['default'],
    'LazyCourseList': typeof import("../components/CourseList.vue")['default'],
    'LazyEmpty': typeof import("../components/Empty.vue")['default'],
    'LazyFavaBtn': typeof import("../components/FavaBtn.vue")['default'],
    'LazyGotoTop': typeof import("../components/GotoTop.vue")['default'],
    'LazyHotCourseList': typeof import("../components/HotCourseList.vue")['default'],
    'LazyImageAd': typeof import("../components/ImageAd.vue")['default'],
    'LazyImageNav': typeof import("../components/ImageNav.vue")['default'],
    'LazyListCard': typeof import("../components/ListCard.vue")['default'],
    'LazyLiveStatusBar': typeof import("../components/LiveStatusBar.vue")['default'],
    'LazyNavBar': typeof import("../components/NavBar.vue")['default'],
    'LazyPageFooter': typeof import("../components/PageFooter.vue")['default'],
    'LazyPaperTestItems': typeof import("../components/PaperTestItems.vue")['default'],
    'LazyPostList': typeof import("../components/PostList.vue")['default'],
    'LazyPrice': typeof import("../components/Price.vue")['default'],
    'LazyQrCode': typeof import("../components/QrCode.vue")['default'],
    'LazySearchBar': typeof import("../components/SearchBar.vue")['default'],
    'LazySeckill': typeof import("../components/Seckill.vue")['default'],
    'LazySendCode': typeof import("../components/SendCode.vue")['default'],
    'LazyTestPaperList': typeof import("../components/TestPaperList.vue")['default'],
    'LazyTimeBox': typeof import("../components/TimeBox.vue")['default'],
    'LazyUploader': typeof import("../components/Uploader.vue")['default'],
    'LazyDetailActiveBar': typeof import("../components/Detail/ActiveBar.vue")['default'],
    'LazyDetailGroupWorks': typeof import("../components/Detail/GroupWorks.vue")['default'],
    'LazyDetailMenu': typeof import("../components/Detail/Menu.vue")['default'],
    'LazyDetailMenuItem': typeof import("../components/Detail/MenuItem.vue")['default'],
    'LazyLoadingBookSkeletion': typeof import("../components/Loading/BookSkeletion.vue")['default'],
    'LazyLoadingCourseSkeleton': typeof import("../components/Loading/CourseSkeleton.vue")['default'],
    'LazyLoadingGroup': typeof import("../components/Loading/Group.vue")['default'],
    'LazyLoadingSkeleton': typeof import("../components/Loading/Skeleton.vue")['default'],
    'LazyPlayerAudio': typeof import("../components/Player/Audio.vue")['default'],
    'LazyPlayerLive': typeof import("../components/Player/Live.vue")['default'],
    'LazyPlayerVideo': typeof import("../components/Player/Video.vue")['default'],
    'LazyUiImage': typeof import("../components/Ui/Image.vue")['default'],
    'LazyUiMenu': typeof import("../components/Ui/Menu.vue")['default'],
    'LazyUiMenuItem': typeof import("../components/Ui/MenuItem.vue")['default'],
    'LazyUiTab': typeof import("../components/Ui/Tab.vue")['default'],
    'LazyUiTabItem': typeof import("../components/Ui/TabItem.vue")['default'],
    'LazyUserBuyList': typeof import("../components/User/BuyList.vue")['default'],
    'LazyUserCouponList': typeof import("../components/User/CouponList.vue")['default'],
    'LazyUserFavaList': typeof import("../components/User/FavaList.vue")['default'],
    'LazyUserHistoryList': typeof import("../components/User/HistoryList.vue")['default'],
    'LazyUserTestList': typeof import("../components/User/TestList.vue")['default'],
    'LazyUiCardBody': typeof import("../components/Ui/Card/Body.vue")['default'],
    'LazyUiCardFooter': typeof import("../components/Ui/Card/Footer.vue")['default'],
    'LazyUiCardHeader': typeof import("../components/Ui/Card/Header.vue")['default'],
    'LazyUiCard': typeof import("../components/Ui/Card/index.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  }
}
export const Banner: typeof import("../components/Banner.vue")['default']
export const BbsTabs: typeof import("../components/BbsTabs.vue")['default']
export const BookList: typeof import("../components/BookList.vue")['default']
export const Comment: typeof import("../components/Comment.vue")['default']
export const CouponList: typeof import("../components/CouponList.vue")['default']
export const CouponModal: typeof import("../components/CouponModal.vue")['default']
export const CourseList: typeof import("../components/CourseList.vue")['default']
export const Empty: typeof import("../components/Empty.vue")['default']
export const FavaBtn: typeof import("../components/FavaBtn.vue")['default']
export const GotoTop: typeof import("../components/GotoTop.vue")['default']
export const HotCourseList: typeof import("../components/HotCourseList.vue")['default']
export const ImageAd: typeof import("../components/ImageAd.vue")['default']
export const ImageNav: typeof import("../components/ImageNav.vue")['default']
export const ListCard: typeof import("../components/ListCard.vue")['default']
export const LiveStatusBar: typeof import("../components/LiveStatusBar.vue")['default']
export const NavBar: typeof import("../components/NavBar.vue")['default']
export const PageFooter: typeof import("../components/PageFooter.vue")['default']
export const PaperTestItems: typeof import("../components/PaperTestItems.vue")['default']
export const PostList: typeof import("../components/PostList.vue")['default']
export const Price: typeof import("../components/Price.vue")['default']
export const QrCode: typeof import("../components/QrCode.vue")['default']
export const SearchBar: typeof import("../components/SearchBar.vue")['default']
export const Seckill: typeof import("../components/Seckill.vue")['default']
export const SendCode: typeof import("../components/SendCode.vue")['default']
export const TestPaperList: typeof import("../components/TestPaperList.vue")['default']
export const TimeBox: typeof import("../components/TimeBox.vue")['default']
export const Uploader: typeof import("../components/Uploader.vue")['default']
export const DetailActiveBar: typeof import("../components/Detail/ActiveBar.vue")['default']
export const DetailGroupWorks: typeof import("../components/Detail/GroupWorks.vue")['default']
export const DetailMenu: typeof import("../components/Detail/Menu.vue")['default']
export const DetailMenuItem: typeof import("../components/Detail/MenuItem.vue")['default']
export const LoadingBookSkeletion: typeof import("../components/Loading/BookSkeletion.vue")['default']
export const LoadingCourseSkeleton: typeof import("../components/Loading/CourseSkeleton.vue")['default']
export const LoadingGroup: typeof import("../components/Loading/Group.vue")['default']
export const LoadingSkeleton: typeof import("../components/Loading/Skeleton.vue")['default']
export const PlayerAudio: typeof import("../components/Player/Audio.vue")['default']
export const PlayerLive: typeof import("../components/Player/Live.vue")['default']
export const PlayerVideo: typeof import("../components/Player/Video.vue")['default']
export const UiImage: typeof import("../components/Ui/Image.vue")['default']
export const UiMenu: typeof import("../components/Ui/Menu.vue")['default']
export const UiMenuItem: typeof import("../components/Ui/MenuItem.vue")['default']
export const UiTab: typeof import("../components/Ui/Tab.vue")['default']
export const UiTabItem: typeof import("../components/Ui/TabItem.vue")['default']
export const UserBuyList: typeof import("../components/User/BuyList.vue")['default']
export const UserCouponList: typeof import("../components/User/CouponList.vue")['default']
export const UserFavaList: typeof import("../components/User/FavaList.vue")['default']
export const UserHistoryList: typeof import("../components/User/HistoryList.vue")['default']
export const UserTestList: typeof import("../components/User/TestList.vue")['default']
export const UiCardBody: typeof import("../components/Ui/Card/Body.vue")['default']
export const UiCardFooter: typeof import("../components/Ui/Card/Footer.vue")['default']
export const UiCardHeader: typeof import("../components/Ui/Card/Header.vue")['default']
export const UiCard: typeof import("../components/Ui/Card/index.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyBanner: typeof import("../components/Banner.vue")['default']
export const LazyBbsTabs: typeof import("../components/BbsTabs.vue")['default']
export const LazyBookList: typeof import("../components/BookList.vue")['default']
export const LazyComment: typeof import("../components/Comment.vue")['default']
export const LazyCouponList: typeof import("../components/CouponList.vue")['default']
export const LazyCouponModal: typeof import("../components/CouponModal.vue")['default']
export const LazyCourseList: typeof import("../components/CourseList.vue")['default']
export const LazyEmpty: typeof import("../components/Empty.vue")['default']
export const LazyFavaBtn: typeof import("../components/FavaBtn.vue")['default']
export const LazyGotoTop: typeof import("../components/GotoTop.vue")['default']
export const LazyHotCourseList: typeof import("../components/HotCourseList.vue")['default']
export const LazyImageAd: typeof import("../components/ImageAd.vue")['default']
export const LazyImageNav: typeof import("../components/ImageNav.vue")['default']
export const LazyListCard: typeof import("../components/ListCard.vue")['default']
export const LazyLiveStatusBar: typeof import("../components/LiveStatusBar.vue")['default']
export const LazyNavBar: typeof import("../components/NavBar.vue")['default']
export const LazyPageFooter: typeof import("../components/PageFooter.vue")['default']
export const LazyPaperTestItems: typeof import("../components/PaperTestItems.vue")['default']
export const LazyPostList: typeof import("../components/PostList.vue")['default']
export const LazyPrice: typeof import("../components/Price.vue")['default']
export const LazyQrCode: typeof import("../components/QrCode.vue")['default']
export const LazySearchBar: typeof import("../components/SearchBar.vue")['default']
export const LazySeckill: typeof import("../components/Seckill.vue")['default']
export const LazySendCode: typeof import("../components/SendCode.vue")['default']
export const LazyTestPaperList: typeof import("../components/TestPaperList.vue")['default']
export const LazyTimeBox: typeof import("../components/TimeBox.vue")['default']
export const LazyUploader: typeof import("../components/Uploader.vue")['default']
export const LazyDetailActiveBar: typeof import("../components/Detail/ActiveBar.vue")['default']
export const LazyDetailGroupWorks: typeof import("../components/Detail/GroupWorks.vue")['default']
export const LazyDetailMenu: typeof import("../components/Detail/Menu.vue")['default']
export const LazyDetailMenuItem: typeof import("../components/Detail/MenuItem.vue")['default']
export const LazyLoadingBookSkeletion: typeof import("../components/Loading/BookSkeletion.vue")['default']
export const LazyLoadingCourseSkeleton: typeof import("../components/Loading/CourseSkeleton.vue")['default']
export const LazyLoadingGroup: typeof import("../components/Loading/Group.vue")['default']
export const LazyLoadingSkeleton: typeof import("../components/Loading/Skeleton.vue")['default']
export const LazyPlayerAudio: typeof import("../components/Player/Audio.vue")['default']
export const LazyPlayerLive: typeof import("../components/Player/Live.vue")['default']
export const LazyPlayerVideo: typeof import("../components/Player/Video.vue")['default']
export const LazyUiImage: typeof import("../components/Ui/Image.vue")['default']
export const LazyUiMenu: typeof import("../components/Ui/Menu.vue")['default']
export const LazyUiMenuItem: typeof import("../components/Ui/MenuItem.vue")['default']
export const LazyUiTab: typeof import("../components/Ui/Tab.vue")['default']
export const LazyUiTabItem: typeof import("../components/Ui/TabItem.vue")['default']
export const LazyUserBuyList: typeof import("../components/User/BuyList.vue")['default']
export const LazyUserCouponList: typeof import("../components/User/CouponList.vue")['default']
export const LazyUserFavaList: typeof import("../components/User/FavaList.vue")['default']
export const LazyUserHistoryList: typeof import("../components/User/HistoryList.vue")['default']
export const LazyUserTestList: typeof import("../components/User/TestList.vue")['default']
export const LazyUiCardBody: typeof import("../components/Ui/Card/Body.vue")['default']
export const LazyUiCardFooter: typeof import("../components/Ui/Card/Footer.vue")['default']
export const LazyUiCardHeader: typeof import("../components/Ui/Card/Header.vue")['default']
export const LazyUiCard: typeof import("../components/Ui/Card/index.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const componentNames: string[]
