// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Banner': typeof import("../components/Banner.vue")['default'],
    'ImageNav': typeof import("../components/ImageNav.vue")['default'],
    'NavBar': typeof import("../components/NavBar.vue")['default'],
    'PageFooter': typeof import("../components/PageFooter.vue")['default'],
    'UiMenu': typeof import("../components/Ui/Menu.vue")['default'],
    'UiMenuItem': typeof import("../components/Ui/MenuItem.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyBanner': typeof import("../components/Banner.vue")['default'],
    'LazyImageNav': typeof import("../components/ImageNav.vue")['default'],
    'LazyNavBar': typeof import("../components/NavBar.vue")['default'],
    'LazyPageFooter': typeof import("../components/PageFooter.vue")['default'],
    'LazyUiMenu': typeof import("../components/Ui/Menu.vue")['default'],
    'LazyUiMenuItem': typeof import("../components/Ui/MenuItem.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  }
}
export const Banner: typeof import("../components/Banner.vue")['default']
export const ImageNav: typeof import("../components/ImageNav.vue")['default']
export const NavBar: typeof import("../components/NavBar.vue")['default']
export const PageFooter: typeof import("../components/PageFooter.vue")['default']
export const UiMenu: typeof import("../components/Ui/Menu.vue")['default']
export const UiMenuItem: typeof import("../components/Ui/MenuItem.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyBanner: typeof import("../components/Banner.vue")['default']
export const LazyImageNav: typeof import("../components/ImageNav.vue")['default']
export const LazyNavBar: typeof import("../components/NavBar.vue")['default']
export const LazyPageFooter: typeof import("../components/PageFooter.vue")['default']
export const LazyUiMenu: typeof import("../components/Ui/Menu.vue")['default']
export const LazyUiMenuItem: typeof import("../components/Ui/MenuItem.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const componentNames: string[]
